#!/bin/sh
# prerm script for slopscale-flowd.

set -e

case "$1" in
    remove)
      if [ -d /run/systemd/system ]; then
          deb-systemd-invoke stop slopscale-flowd.service >/dev/null || true
      fi
    ;;

    upgrade|deconfigure|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac
