# Issues must have some content
blank_issues_enabled: false

# Contact links
contact_links:
  - name: "slopscale discussions"
    url: "https://github.com/aislopware/slopscale/discussions"
    about: "Please ask and answer questions about usage of slopscale here."
  - name: "slopscale usage documentation"
    url: "https://aislopware.github.io/slopscale/"
    about: "Find documentation about how to configure and run slopscale."
