// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by tailscale/cmd/viewer; DO NOT EDIT.

package types

import (
	"database/sql"
	jsonv1 "encoding/json"
	"errors"
	"net/netip"
	"time"

	jsonv2 "github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
	"tailscale.com/tailcfg"
	"tailscale.com/types/key"
	"tailscale.com/types/views"
)

//go:generate go run tailscale.com/cmd/cloner  -clonefunc=false -type=User,Node,PreAuthKey,PostureIdentity,NodeAttribute

// View returns a read-only view of User.
func (p *User) View() UserView {
	return UserView{ж: p}
}

// UserView provides a read-only view over User.
//
// Its methods should only be called if `Valid()` returns true.
type UserView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *User
}

// Valid reports whether v's underlying value is non-nil.
func (v UserView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v UserView) AsStruct() *User {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v UserView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v UserView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *UserView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x User
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *UserView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x User
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v UserView) ID() uint             { return v.ж.ID }
func (v UserView) CreatedAt() time.Time { return v.ж.CreatedAt }
func (v UserView) UpdatedAt() time.Time { return v.ж.UpdatedAt }

// DeletedAt marks a soft-deleted user; reads skip rows that carry it.
func (v UserView) DeletedAt() views.ValuePointer[time.Time] {
	return views.ValuePointerOf(v.ж.DeletedAt)
}

// Name (username) for the user, is used if email is empty
// Should not be used, please use [User.Username].
// It is unique if [User.ProviderIdentifier] is not set.
func (v UserView) Name() string { return v.ж.Name }

// Typically the full name of the user
func (v UserView) DisplayName() string { return v.ж.DisplayName }

// Email of the user
// Should not be used, please use [User.Username].
func (v UserView) Email() string { return v.ж.Email }

// ProviderIdentifier is a unique or not set identifier of the
// user from OIDC. It is the combination of `iss`
// and `sub` claim in the OIDC token.
// It is unique if set.
// It is unique together with [User.Name].
func (v UserView) ProviderIdentifier() sql.NullString { return v.ж.ProviderIdentifier }

// Provider is the origin of the user account,
// same as RegistrationMethod, without authkey.
func (v UserView) Provider() string { return v.ж.Provider }

// TODO(kradalby): See if we can fill in Gravatar here.
func (v UserView) ProfilePicURL() string { return v.ж.ProfilePicURL }

// Role is the user's administrative role; see [Role]. Rows from before
// roles existed hold "member".
func (v UserView) Role() Role { return v.ж.Role }

// ApprovedAt is when the user was admitted to the tailnet. Nil while
// a user created by OIDC login waits for an administrator (users
// approval); such a user cannot register nodes. Users created by an
// administrator are approved on creation.
func (v UserView) ApprovedAt() views.ValuePointer[time.Time] {
	return views.ValuePointerOf(v.ж.ApprovedAt)
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _UserViewNeedsRegeneration = User(struct {
	ID                 uint
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	Name               string
	DisplayName        string
	Email              string
	ProviderIdentifier sql.NullString
	Provider           string
	ProfilePicURL      string
	Role               Role
	ApprovedAt         *time.Time
}{})

// View returns a read-only view of Node.
func (p *Node) View() NodeView {
	return NodeView{ж: p}
}

// NodeView provides a read-only view over Node.
//
// Its methods should only be called if `Valid()` returns true.
type NodeView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *Node
}

// Valid reports whether v's underlying value is non-nil.
func (v NodeView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v NodeView) AsStruct() *Node {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v NodeView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v NodeView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *NodeView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x Node
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *NodeView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x Node
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v NodeView) ID() NodeID                             { return v.ж.ID }
func (v NodeView) MachineKey() key.MachinePublic          { return v.ж.MachineKey }
func (v NodeView) NodeKey() key.NodePublic                { return v.ж.NodeKey }
func (v NodeView) DiscoKey() key.DiscoPublic              { return v.ж.DiscoKey }
func (v NodeView) Endpoints() views.Slice[netip.AddrPort] { return views.SliceOf(v.ж.Endpoints) }
func (v NodeView) Hostinfo() tailcfg.HostinfoView         { return v.ж.Hostinfo.View() }
func (v NodeView) IPv4() views.ValuePointer[netip.Addr]   { return views.ValuePointerOf(v.ж.IPv4) }

func (v NodeView) IPv6() views.ValuePointer[netip.Addr] { return views.ValuePointerOf(v.ж.IPv6) }

// Hostname represents the name given by the Tailscale
// client during registration
func (v NodeView) Hostname() string { return v.ж.Hostname }

// Givenname represents either:
// a DNS normalized version of [Node.Hostname]
// a valid name set by the [User]
//
// GivenName is the name used in all DNS related
// parts of slopscale.
func (v NodeView) GivenName() string { return v.ж.GivenName }

// UserID identifies the owning user for user-owned nodes.
// Nil for tagged nodes, which are owned by their tags.
func (v NodeView) UserID() views.ValuePointer[uint] { return views.ValuePointerOf(v.ж.UserID) }

func (v NodeView) User() UserView         { return v.ж.User.View() }
func (v NodeView) RegisterMethod() string { return v.ж.RegisterMethod }

// Tags is the definitive owner for tagged nodes.
// When non-empty, the node is "tagged" and tags define its identity.
// Empty for user-owned nodes.
// Tags cannot be removed once set (one-way transition).
func (v NodeView) Tags() views.Slice[string] { return views.SliceOf(v.ж.Tags) }

// When a node has been created with a [PreAuthKey], we need to
// prevent the preauthkey from being deleted before the node.
// The preauthkey can define "tags" of the node so we need it
// around.
func (v NodeView) AuthKeyID() views.ValuePointer[uint64] { return views.ValuePointerOf(v.ж.AuthKeyID) }

func (v NodeView) AuthKey() PreAuthKeyView               { return v.ж.AuthKey.View() }
func (v NodeView) Expiry() views.ValuePointer[time.Time] { return views.ValuePointerOf(v.ж.Expiry) }

// LastSeen is when the node was last in contact with
// slopscale. It is best effort and not persisted.
func (v NodeView) LastSeen() views.ValuePointer[time.Time] {
	return views.ValuePointerOf(v.ж.LastSeen)
}

// ApprovedRoutes is a list of routes that the node is allowed to announce
// as a subnet router. They are not necessarily the routes that the node
// announces at the moment.
// See [Node.Hostinfo]
func (v NodeView) ApprovedRoutes() views.Slice[netip.Prefix] {
	return views.SliceOf(v.ж.ApprovedRoutes)
}

// ApprovedAt is when an administrator (or the registration itself,
// when device approval is off or the pre-auth key is preauthorized)
// admitted the node to the tailnet. Nil while the node waits for
// approval: it then gets no peers and no peer sees it.
func (v NodeView) ApprovedAt() views.ValuePointer[time.Time] {
	return views.ValuePointerOf(v.ж.ApprovedAt)
}

// SuspendedAt is set while an administrator has suspended the node.
// A suspended node stays registered and keeps its addresses, but it
// gets no peers, no peer sees it and its client is told it is not
// authorized. Only [State.SetNodeSuspension] writes it; the map
// request path leaves it alone like [Node.ApprovedAt].
func (v NodeView) SuspendedAt() views.ValuePointer[time.Time] {
	return views.ValuePointerOf(v.ж.SuspendedAt)
}

// Posture is the device identity the client last reported over c2n,
// nil until the server asked. Only [State.CollectPosture] writes it.
func (v NodeView) Posture() PostureIdentityView { return v.ж.Posture.View() }

// Attributes are the custom posture attributes set through the API,
// in key order, expired ones included until the sweeper drops them.
// Only the attribute operations on State write them.
func (v NodeView) Attributes() views.Slice[NodeAttribute] { return views.SliceOf(v.ж.Attributes) }

// SourceAddr is the address the node's control connection last came
// from, as the trusted-proxy middleware resolved it. It is runtime
// state, never stored, and feeds the ip: posture attributes.
func (v NodeView) SourceAddr() netip.Addr { return v.ж.SourceAddr }

// SharedWith lists the users the node has been shared with, in
// ascending id order. The policy resolves autogroup:shared from it
// and the map response marks the node as shared to those users'
// nodes. Only [State.ShareNode] and [State.UnshareNode] write it.
func (v NodeView) SharedWith() views.Slice[UserID] { return views.SliceOf(v.ж.SharedWith) }

// GlobalExitNode marks an exit node every client is told to prefer:
// the node carries suggest-exit-node and every node auto-exit-node
// while at least one global exit node exists. Its exit routes are
// approved when it is set. Only [State.SetGlobalExitNode] writes it.
func (v NodeView) GlobalExitNode() bool { return v.ж.GlobalExitNode }

// Ephemeral is set when the client asked to be ephemeral in its
// register request (a tailscaled with mem: state, a tsnet Server
// with Ephemeral) rather than through an ephemeral pre-auth key.
// [Node.IsEphemeral] reads both; only registration writes it.
func (v NodeView) Ephemeral() bool      { return v.ж.Ephemeral }
func (v NodeView) CreatedAt() time.Time { return v.ж.CreatedAt }
func (v NodeView) UpdatedAt() time.Time { return v.ж.UpdatedAt }
func (v NodeView) DeletedAt() views.ValuePointer[time.Time] {
	return views.ValuePointerOf(v.ж.DeletedAt)
}

func (v NodeView) IsOnline() views.ValuePointer[bool] { return views.ValuePointerOf(v.ж.IsOnline) }

// Unhealthy excludes the node from primary route election while
// online. Written by the HA prober. Runtime-only.
func (v NodeView) Unhealthy() bool { return v.ж.Unhealthy }

// ActiveSessions counts live poll sessions for this node.
// [State.Connect] increments it and every session release
// ([State.Disconnect]) decrements it, so the node goes offline
// exactly when its last session ends, regardless of the order in
// which overlapping sessions' cleanups run. Never persisted, like
// SessionEpoch.
func (v NodeView) ActiveSessions() int { return v.ж.ActiveSessions }

// SessionEpoch identifies a poll session generation; Connect bumps
// it. It complements ActiveSessions rather than duplicating it:
// the epoch is monotonic, which the HA prober needs to detect that
// a probe target reconnected mid-cycle. A refcount can return to
// its old value, a generation cannot. poll.go also uses the epoch
// returned by Connect as a "Connect ran" sentinel for its cleanup,
// and Disconnect logs it. Runtime-only.
func (v NodeView) SessionEpoch() uint64 { return v.ж.SessionEpoch }

// CapVer is the capability version the client last sent in a map
// request, what peers see as [tailcfg.Node.Cap]. Zero until the node
// polls after a restart; the client treats zero as unknown.
// Runtime-only, written by [State.UpdateNodeFromMapRequest].
func (v NodeView) CapVer() tailcfg.CapabilityVersion { return v.ж.CapVer }

// ClientWarnings are the warn-* flags the client last sent in
// [tailcfg.MapRequest.DebugFlags], without the prefix and sorted:
// "ip-forwarding-off" for a subnet router whose kernel drops
// forwarded packets, "router-unhealthy" for a broken route setup,
// "etc-apt-source-disabled" for a commented-out Tailscale apt source,
// and whatever a newer client adds. Runtime-only, written by
// [State.UpdateNodeFromMapRequest] and cleared by [State.Disconnect]
// when the node goes offline.
func (v NodeView) ClientWarnings() views.Slice[string] { return views.SliceOf(v.ж.ClientWarnings) }
func (v NodeView) String() string                      { return v.ж.String() }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _NodeViewNeedsRegeneration = Node(struct {
	ID             NodeID
	MachineKey     key.MachinePublic
	NodeKey        key.NodePublic
	DiscoKey       key.DiscoPublic
	Endpoints      AddrPorts
	Hostinfo       *tailcfg.Hostinfo
	IPv4           *netip.Addr
	IPv6           *netip.Addr
	Hostname       string
	GivenName      string
	UserID         *uint
	User           *User
	RegisterMethod string
	Tags           Strings
	AuthKeyID      *uint64
	AuthKey        *PreAuthKey
	Expiry         *time.Time
	LastSeen       *time.Time
	ApprovedRoutes Prefixes
	ApprovedAt     *time.Time
	SuspendedAt    *time.Time
	Posture        *PostureIdentity
	Attributes     []NodeAttribute
	SourceAddr     netip.Addr
	SharedWith     []UserID
	GlobalExitNode bool
	Ephemeral      bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
	IsOnline       *bool
	Unhealthy      bool
	ActiveSessions int
	SessionEpoch   uint64
	CapVer         tailcfg.CapabilityVersion
	ClientWarnings []string
}{})

// View returns a read-only view of PreAuthKey.
func (p *PreAuthKey) View() PreAuthKeyView {
	return PreAuthKeyView{ж: p}
}

// PreAuthKeyView provides a read-only view over PreAuthKey.
//
// Its methods should only be called if `Valid()` returns true.
type PreAuthKeyView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *PreAuthKey
}

// Valid reports whether v's underlying value is non-nil.
func (v PreAuthKeyView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v PreAuthKeyView) AsStruct() *PreAuthKey {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v PreAuthKeyView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v PreAuthKeyView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *PreAuthKeyView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x PreAuthKey
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *PreAuthKeyView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x PreAuthKey
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v PreAuthKeyView) ID() uint64 { return v.ж.ID }

// Legacy plaintext key (for backwards compatibility)
func (v PreAuthKeyView) Key() string { return v.ж.Key }

// New bcrypt-based authentication
func (v PreAuthKeyView) Prefix() string { return v.ж.Prefix }

// bcrypt
func (v PreAuthKeyView) Hash() views.ByteSlice[[]byte] { return views.ByteSliceOf(v.ж.Hash) }

// For tagged keys: [PreAuthKey.UserID] tracks who created the key (informational)
// For user-owned keys: [PreAuthKey.UserID] tracks the node owner
// Can be nil for system-created tagged keys
func (v PreAuthKeyView) UserID() views.ValuePointer[uint] { return views.ValuePointerOf(v.ж.UserID) }

func (v PreAuthKeyView) User() UserView { return v.ж.User.View() }

// Free-text description, set via the v2 API. Empty for keys created through
// the v1 API or CLI.
func (v PreAuthKeyView) Description() string { return v.ж.Description }

// Preauthorized keys register nodes as approved even while device
// approval is on. Keys created before the switch existed are
// preauthorized.
func (v PreAuthKeyView) Preauthorized() bool { return v.ж.Preauthorized }
func (v PreAuthKeyView) Reusable() bool      { return v.ж.Reusable }
func (v PreAuthKeyView) Ephemeral() bool     { return v.ж.Ephemeral }
func (v PreAuthKeyView) Used() bool          { return v.ж.Used }

// Tags to assign to nodes registered with this key.
// Tags are copied to the node during registration.
// If non-empty, this creates tagged nodes (not user-owned).
func (v PreAuthKeyView) Tags() views.Slice[string] { return views.SliceOf(v.ж.Tags) }

// Groups are the access groups a node registered with this key joins.
// Deleted groups are skipped at registration.
func (v PreAuthKeyView) Groups() views.Slice[GroupID] { return views.SliceOf(v.ж.Groups) }
func (v PreAuthKeyView) CreatedAt() views.ValuePointer[time.Time] {
	return views.ValuePointerOf(v.ж.CreatedAt)
}

func (v PreAuthKeyView) Expiration() views.ValuePointer[time.Time] {
	return views.ValuePointerOf(v.ж.Expiration)
}

// Revoked is set when the key is revoked through the v2 API (Tailscale's
// DELETE). A revoked key is invalid but kept retrievable until the
// background collector reaps it after the configured retention window.
func (v PreAuthKeyView) Revoked() views.ValuePointer[time.Time] {
	return views.ValuePointerOf(v.ж.Revoked)
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _PreAuthKeyViewNeedsRegeneration = PreAuthKey(struct {
	ID            uint64
	Key           string
	Prefix        string
	Hash          []byte
	UserID        *uint
	User          *User
	Description   string
	Preauthorized bool
	Reusable      bool
	Ephemeral     bool
	Used          bool
	Tags          []string
	Groups        []GroupID
	CreatedAt     *time.Time
	Expiration    *time.Time
	Revoked       *time.Time
}{})

// View returns a read-only view of PostureIdentity.
func (p *PostureIdentity) View() PostureIdentityView {
	return PostureIdentityView{ж: p}
}

// PostureIdentityView provides a read-only view over PostureIdentity.
//
// Its methods should only be called if `Valid()` returns true.
type PostureIdentityView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *PostureIdentity
}

// Valid reports whether v's underlying value is non-nil.
func (v PostureIdentityView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v PostureIdentityView) AsStruct() *PostureIdentity {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v PostureIdentityView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v PostureIdentityView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *PostureIdentityView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x PostureIdentity
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *PostureIdentityView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x PostureIdentity
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// SerialNumbers are the hardware serial numbers the client found,
// empty when it found none or refused.
func (v PostureIdentityView) SerialNumbers() views.Slice[string] {
	return views.SliceOf(v.ж.SerialNumbers)
}

// Disabled is set when the client has posture checking switched off
// (`tailscale set --posture-checking=false`, or an MDM key), in which
// case it reports nothing.
func (v PostureIdentityView) Disabled() bool { return v.ж.Disabled }

// CollectedAt is when the client answered.
func (v PostureIdentityView) CollectedAt() time.Time { return v.ж.CollectedAt }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _PostureIdentityViewNeedsRegeneration = PostureIdentity(struct {
	SerialNumbers []string
	Disabled      bool
	CollectedAt   time.Time
}{})

// View returns a read-only view of NodeAttribute.
func (p *NodeAttribute) View() NodeAttributeView {
	return NodeAttributeView{ж: p}
}

// NodeAttributeView provides a read-only view over NodeAttribute.
//
// Its methods should only be called if `Valid()` returns true.
type NodeAttributeView struct {
	// ж is the underlying mutable value, named with a hard-to-type
	// character that looks pointy like a pointer.
	// It is named distinctively to make you think of how dangerous it is to escape
	// to callers. You must not let callers be able to mutate it.
	ж *NodeAttribute
}

// Valid reports whether v's underlying value is non-nil.
func (v NodeAttributeView) Valid() bool { return v.ж != nil }

// AsStruct returns a clone of the underlying value which aliases no memory with
// the original.
func (v NodeAttributeView) AsStruct() *NodeAttribute {
	if v.ж == nil {
		return nil
	}
	return v.ж.Clone()
}

// MarshalJSON implements [jsonv1.Marshaler].
func (v NodeAttributeView) MarshalJSON() ([]byte, error) {
	return jsonv1.Marshal(v.ж)
}

// MarshalJSONTo implements [jsonv2.MarshalerTo].
func (v NodeAttributeView) MarshalJSONTo(enc *jsontext.Encoder) error {
	return jsonv2.MarshalEncode(enc, v.ж)
}

// UnmarshalJSON implements [jsonv1.Unmarshaler].
func (v *NodeAttributeView) UnmarshalJSON(b []byte) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	if len(b) == 0 {
		return nil
	}
	var x NodeAttribute
	if err := jsonv1.Unmarshal(b, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

// UnmarshalJSONFrom implements [jsonv2.UnmarshalerFrom].
func (v *NodeAttributeView) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if v.ж != nil {
		return errors.New("already initialized")
	}
	var x NodeAttribute
	if err := jsonv2.UnmarshalDecode(dec, &x); err != nil {
		return err
	}
	v.ж = &x
	return nil
}

func (v NodeAttributeView) Key() string           { return v.ж.Key }
func (v NodeAttributeView) Value() AttributeValue { return v.ж.Value }

// ExpiresAt, when not zero, is when the attribute disappears on its
// own.
func (v NodeAttributeView) ExpiresAt() time.Time { return v.ж.ExpiresAt }
func (v NodeAttributeView) Comment() string      { return v.ж.Comment }

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _NodeAttributeViewNeedsRegeneration = NodeAttribute(struct {
	Key       string
	Value     AttributeValue
	ExpiresAt time.Time
	Comment   string
}{})
