// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by tailscale.com/cmd/cloner; DO NOT EDIT.

package types

import (
	"database/sql"
	"net/netip"
	"time"

	"tailscale.com/tailcfg"
	"tailscale.com/types/key"
)

// Clone makes a deep copy of User.
// The result aliases no memory with the original.
func (src *User) Clone() *User {
	if src == nil {
		return nil
	}
	dst := new(User)
	*dst = *src
	if dst.DeletedAt != nil {
		dst.DeletedAt = new(*src.DeletedAt)
	}
	if dst.ApprovedAt != nil {
		dst.ApprovedAt = new(*src.ApprovedAt)
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _UserCloneNeedsRegeneration = User(struct {
	ID                 uint
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	Name               string
	DisplayName        string
	Email              string
	ProviderIdentifier sql.NullString
	Provider           string
	ProfilePicURL      string
	Role               Role
	ApprovedAt         *time.Time
}{})

// Clone makes a deep copy of Node.
// The result aliases no memory with the original.
func (src *Node) Clone() *Node {
	if src == nil {
		return nil
	}
	dst := new(Node)
	*dst = *src
	dst.Endpoints = append(src.Endpoints[:0:0], src.Endpoints...)
	dst.Hostinfo = src.Hostinfo.Clone()
	if dst.IPv4 != nil {
		dst.IPv4 = new(*src.IPv4)
	}
	if dst.IPv6 != nil {
		dst.IPv6 = new(*src.IPv6)
	}
	if dst.UserID != nil {
		dst.UserID = new(*src.UserID)
	}
	dst.User = src.User.Clone()
	dst.Tags = append(src.Tags[:0:0], src.Tags...)
	if dst.AuthKeyID != nil {
		dst.AuthKeyID = new(*src.AuthKeyID)
	}
	dst.AuthKey = src.AuthKey.Clone()
	if dst.Expiry != nil {
		dst.Expiry = new(*src.Expiry)
	}
	if dst.LastSeen != nil {
		dst.LastSeen = new(*src.LastSeen)
	}
	dst.ApprovedRoutes = append(src.ApprovedRoutes[:0:0], src.ApprovedRoutes...)
	if dst.ApprovedAt != nil {
		dst.ApprovedAt = new(*src.ApprovedAt)
	}
	if dst.SuspendedAt != nil {
		dst.SuspendedAt = new(*src.SuspendedAt)
	}
	dst.Posture = src.Posture.Clone()
	dst.Attributes = append(src.Attributes[:0:0], src.Attributes...)
	dst.Services = src.Services.Clone()
	dst.ApprovedServices = append(src.ApprovedServices[:0:0], src.ApprovedServices...)
	dst.SharedWith = append(src.SharedWith[:0:0], src.SharedWith...)
	if dst.DeletedAt != nil {
		dst.DeletedAt = new(*src.DeletedAt)
	}
	if dst.IsOnline != nil {
		dst.IsOnline = new(*src.IsOnline)
	}
	dst.ClientWarnings = append(src.ClientWarnings[:0:0], src.ClientWarnings...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _NodeCloneNeedsRegeneration = Node(struct {
	ID               NodeID
	MachineKey       key.MachinePublic
	NodeKey          key.NodePublic
	DiscoKey         key.DiscoPublic
	Endpoints        AddrPorts
	Hostinfo         *tailcfg.Hostinfo
	IPv4             *netip.Addr
	IPv6             *netip.Addr
	Hostname         string
	GivenName        string
	UserID           *uint
	User             *User
	RegisterMethod   string
	Tags             Strings
	AuthKeyID        *uint64
	AuthKey          *PreAuthKey
	Expiry           *time.Time
	LastSeen         *time.Time
	ApprovedRoutes   Prefixes
	ApprovedAt       *time.Time
	SuspendedAt      *time.Time
	Posture          *PostureIdentity
	Attributes       []NodeAttribute
	Services         *NodeServices
	ApprovedServices []string
	SourceAddr       netip.Addr
	SharedWith       []UserID
	GlobalExitNode   bool
	Ephemeral        bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time
	IsOnline         *bool
	Unhealthy        bool
	ActiveSessions   int
	SessionEpoch     uint64
	CapVer           tailcfg.CapabilityVersion
	ClientWarnings   []string
}{})

// Clone makes a deep copy of PreAuthKey.
// The result aliases no memory with the original.
func (src *PreAuthKey) Clone() *PreAuthKey {
	if src == nil {
		return nil
	}
	dst := new(PreAuthKey)
	*dst = *src
	dst.Hash = append(src.Hash[:0:0], src.Hash...)
	if dst.UserID != nil {
		dst.UserID = new(*src.UserID)
	}
	dst.User = src.User.Clone()
	dst.Tags = append(src.Tags[:0:0], src.Tags...)
	dst.Groups = append(src.Groups[:0:0], src.Groups...)
	if dst.CreatedAt != nil {
		dst.CreatedAt = new(*src.CreatedAt)
	}
	if dst.Expiration != nil {
		dst.Expiration = new(*src.Expiration)
	}
	if dst.Revoked != nil {
		dst.Revoked = new(*src.Revoked)
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _PreAuthKeyCloneNeedsRegeneration = PreAuthKey(struct {
	ID            uint64
	Key           string
	Prefix        string
	Hash          []byte
	UserID        *uint
	User          *User
	Description   string
	Preauthorized bool
	Reusable      bool
	Ephemeral     bool
	Used          bool
	Tags          []string
	Groups        []GroupID
	CreatedAt     *time.Time
	Expiration    *time.Time
	Revoked       *time.Time
}{})

// Clone makes a deep copy of PostureIdentity.
// The result aliases no memory with the original.
func (src *PostureIdentity) Clone() *PostureIdentity {
	if src == nil {
		return nil
	}
	dst := new(PostureIdentity)
	*dst = *src
	dst.SerialNumbers = append(src.SerialNumbers[:0:0], src.SerialNumbers...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _PostureIdentityCloneNeedsRegeneration = PostureIdentity(struct {
	SerialNumbers []string
	Disabled      bool
	CollectedAt   time.Time
}{})

// Clone makes a deep copy of NodeAttribute.
// The result aliases no memory with the original.
func (src *NodeAttribute) Clone() *NodeAttribute {
	if src == nil {
		return nil
	}
	dst := new(NodeAttribute)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _NodeAttributeCloneNeedsRegeneration = NodeAttribute(struct {
	Key       string
	Value     AttributeValue
	ExpiresAt time.Time
	Comment   string
}{})

// Clone makes a deep copy of NodeServices.
// The result aliases no memory with the original.
func (src *NodeServices) Clone() *NodeServices {
	if src == nil {
		return nil
	}
	dst := new(NodeServices)
	*dst = *src
	if src.Services != nil {
		dst.Services = make([]tailcfg.VIPService, len(src.Services))
		for i := range dst.Services {
			dst.Services[i] = *src.Services[i].Clone()
		}
	}
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _NodeServicesCloneNeedsRegeneration = NodeServices(struct {
	Hash     string
	Services []tailcfg.VIPService
}{})
