#!/bin/sh
# postinst script for slopscale.

set -e

# Summary of how this script can be called:
#        * <postinst> 'configure' <most-recently-configured-version>
#        * <old-postinst> 'abort-upgrade' <new version>
#        * <conflictor's-postinst> 'abort-remove' 'in-favour' <package>
#          <new-version>
#        * <postinst> 'abort-remove'
#        * <deconfigured's-postinst> 'abort-deconfigure' 'in-favour'
#          <failed-install-package> <version> 'removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package.

SLOPSCALE_USER="slopscale"
SLOPSCALE_GROUP="slopscale"
SLOPSCALE_HOME_DIR="/var/lib/slopscale"
SLOPSCALE_SHELL="/usr/sbin/nologin"
SLOPSCALE_SERVICE="slopscale.service"

case "$1" in
    configure)
      groupadd --force --system "$SLOPSCALE_GROUP"
      if ! id -u "$SLOPSCALE_USER" >/dev/null 2>&1; then
        useradd --system --shell "$SLOPSCALE_SHELL" \
          --gid "$SLOPSCALE_GROUP" --home-dir "$SLOPSCALE_HOME_DIR" \
          --comment "slopscale default user" "$SLOPSCALE_USER"
      fi

      # Enable service and keep track of its state
      if deb-systemd-helper --quiet was-enabled "$SLOPSCALE_SERVICE"; then
        deb-systemd-helper enable "$SLOPSCALE_SERVICE" >/dev/null || true
      else
        deb-systemd-helper update-state "$SLOPSCALE_SERVICE" >/dev/null || true
      fi

      # Bounce service
      if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        if [ -n "$2" ]; then
          deb-systemd-invoke restart "$SLOPSCALE_SERVICE" >/dev/null || true
        else
          deb-systemd-invoke start "$SLOPSCALE_SERVICE" >/dev/null || true
        fi
      fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac
