/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppAppsRouteImport } from './routes/_app/apps'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppNetworksRouteImport } from './routes/_app/networks'
import { Route as AppRoutesRouteImport } from './routes/_app/routes'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppSignInsRouteImport } from './routes/_app/sign-ins'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppDnsIndexRouteImport } from './routes/_app/dns/index'
import { Route as AppDnsNameserversRouteImport } from './routes/_app/dns/nameservers'
import { Route as AppDnsRecordsRouteImport } from './routes/_app/dns/records'
import { Route as AppDnsSplitRouteImport } from './routes/_app/dns/split'
import { Route as AppIntegrationsIndexRouteImport } from './routes/_app/integrations/index'
import { Route as AppIntegrationsLogStreamsRouteImport } from './routes/_app/integrations/log-streams'
import { Route as AppIntegrationsPostureRouteImport } from './routes/_app/integrations/posture'
import { Route as AppIntegrationsWebhooksRouteImport } from './routes/_app/integrations/webhooks'
import { Route as AppKeysIndexRouteImport } from './routes/_app/keys/index'
import { Route as AppKeysApiRouteImport } from './routes/_app/keys/api'
import { Route as AppKeysOauthRouteImport } from './routes/_app/keys/oauth'
import { Route as AppKeysPreAuthRouteImport } from './routes/_app/keys/pre-auth'
import { Route as AppMachinesIndexRouteImport } from './routes/_app/machines/index'
import { Route as AppMachinesNodeIdRouteImport } from './routes/_app/machines/$nodeId'
import { Route as AppPolicyIndexRouteImport } from './routes/_app/policy/index'
import { Route as AppPolicyFileRouteImport } from './routes/_app/policy/file'
import { Route as AppPolicyGraphRouteImport } from './routes/_app/policy/graph'
import { Route as AppPolicyGroupsRouteImport } from './routes/_app/policy/groups'
import { Route as AppPolicyPosturesRouteImport } from './routes/_app/policy/postures'
import { Route as AppPolicyRequestsRouteImport } from './routes/_app/policy/requests'
import { Route as AppPolicyRulesRouteImport } from './routes/_app/policy/rules'
import { Route as AppRelaysIndexRouteImport } from './routes/_app/relays/index'
import { Route as AppRelaysEmbeddedRouteImport } from './routes/_app/relays/embedded'
import { Route as AppRelaysLatencyRouteImport } from './routes/_app/relays/latency'
import { Route as AppRelaysMapRouteImport } from './routes/_app/relays/map'
import { Route as AppRelaysOwnRouteImport } from './routes/_app/relays/own'
import { Route as AppRelaysSourcesRouteImport } from './routes/_app/relays/sources'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppServicesLabelRouteImport } from './routes/_app/services/$label'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsServerRouteImport } from './routes/_app/settings/server'
import { Route as AppSettingsTailnetRouteImport } from './routes/_app/settings/tailnet'
import { Route as AppMachinesNodeIdSshRouteImport } from './routes/_app/machines/$nodeId_.ssh'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsRoute = AppAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksRoute = AppNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInsRoute = AppSignInsRouteImport.update({
  id: '/sign-ins',
  path: '/sign-ins',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppDnsIndexRoute = AppDnsIndexRouteImport.update({
  id: '/dns/',
  path: '/dns/',
  getParentRoute: () => AppRoute,
} as any)
const AppDnsNameserversRoute = AppDnsNameserversRouteImport.update({
  id: '/dns/nameservers',
  path: '/dns/nameservers',
  getParentRoute: () => AppRoute,
} as any)
const AppDnsRecordsRoute = AppDnsRecordsRouteImport.update({
  id: '/dns/records',
  path: '/dns/records',
  getParentRoute: () => AppRoute,
} as any)
const AppDnsSplitRoute = AppDnsSplitRouteImport.update({
  id: '/dns/split',
  path: '/dns/split',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsLogStreamsRoute =
  AppIntegrationsLogStreamsRouteImport.update({
    id: '/integrations/log-streams',
    path: '/integrations/log-streams',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsPostureRoute = AppIntegrationsPostureRouteImport.update({
  id: '/integrations/posture',
  path: '/integrations/posture',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsWebhooksRoute = AppIntegrationsWebhooksRouteImport.update({
  id: '/integrations/webhooks',
  path: '/integrations/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysIndexRoute = AppKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysApiRoute = AppKeysApiRouteImport.update({
  id: '/keys/api',
  path: '/keys/api',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysOauthRoute = AppKeysOauthRouteImport.update({
  id: '/keys/oauth',
  path: '/keys/oauth',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysPreAuthRoute = AppKeysPreAuthRouteImport.update({
  id: '/keys/pre-auth',
  path: '/keys/pre-auth',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesIndexRoute = AppMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesNodeIdRoute = AppMachinesNodeIdRouteImport.update({
  id: '/machines/$nodeId',
  path: '/machines/$nodeId',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyIndexRoute = AppPolicyIndexRouteImport.update({
  id: '/policy/',
  path: '/policy/',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyFileRoute = AppPolicyFileRouteImport.update({
  id: '/policy/file',
  path: '/policy/file',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyGraphRoute = AppPolicyGraphRouteImport.update({
  id: '/policy/graph',
  path: '/policy/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyGroupsRoute = AppPolicyGroupsRouteImport.update({
  id: '/policy/groups',
  path: '/policy/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyPosturesRoute = AppPolicyPosturesRouteImport.update({
  id: '/policy/postures',
  path: '/policy/postures',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyRequestsRoute = AppPolicyRequestsRouteImport.update({
  id: '/policy/requests',
  path: '/policy/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyRulesRoute = AppPolicyRulesRouteImport.update({
  id: '/policy/rules',
  path: '/policy/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppRelaysIndexRoute = AppRelaysIndexRouteImport.update({
  id: '/relays/',
  path: '/relays/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelaysEmbeddedRoute = AppRelaysEmbeddedRouteImport.update({
  id: '/relays/embedded',
  path: '/relays/embedded',
  getParentRoute: () => AppRoute,
} as any)
const AppRelaysLatencyRoute = AppRelaysLatencyRouteImport.update({
  id: '/relays/latency',
  path: '/relays/latency',
  getParentRoute: () => AppRoute,
} as any)
const AppRelaysMapRoute = AppRelaysMapRouteImport.update({
  id: '/relays/map',
  path: '/relays/map',
  getParentRoute: () => AppRoute,
} as any)
const AppRelaysOwnRoute = AppRelaysOwnRouteImport.update({
  id: '/relays/own',
  path: '/relays/own',
  getParentRoute: () => AppRoute,
} as any)
const AppRelaysSourcesRoute = AppRelaysSourcesRouteImport.update({
  id: '/relays/sources',
  path: '/relays/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesLabelRoute = AppServicesLabelRouteImport.update({
  id: '/services/$label',
  path: '/services/$label',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsServerRoute = AppSettingsServerRouteImport.update({
  id: '/settings/server',
  path: '/settings/server',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTailnetRoute = AppSettingsTailnetRouteImport.update({
  id: '/settings/tailnet',
  path: '/settings/tailnet',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesNodeIdSshRoute = AppMachinesNodeIdSshRouteImport.update({
  id: '/machines/$nodeId_/ssh',
  path: '/machines/$nodeId/ssh',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/apps': typeof AppAppsRoute
  '/audit': typeof AppAuditRoute
  '/networks': typeof AppNetworksRoute
  '/routes': typeof AppRoutesRoute
  '/sessions': typeof AppSessionsRoute
  '/sign-ins': typeof AppSignInsRoute
  '/users': typeof AppUsersRoute
  '/dns/nameservers': typeof AppDnsNameserversRoute
  '/dns/records': typeof AppDnsRecordsRoute
  '/dns/split': typeof AppDnsSplitRoute
  '/integrations/log-streams': typeof AppIntegrationsLogStreamsRoute
  '/integrations/posture': typeof AppIntegrationsPostureRoute
  '/integrations/webhooks': typeof AppIntegrationsWebhooksRoute
  '/keys/api': typeof AppKeysApiRoute
  '/keys/oauth': typeof AppKeysOauthRoute
  '/keys/pre-auth': typeof AppKeysPreAuthRoute
  '/machines/$nodeId': typeof AppMachinesNodeIdRoute
  '/policy/file': typeof AppPolicyFileRoute
  '/policy/graph': typeof AppPolicyGraphRoute
  '/policy/groups': typeof AppPolicyGroupsRoute
  '/policy/postures': typeof AppPolicyPosturesRoute
  '/policy/requests': typeof AppPolicyRequestsRoute
  '/policy/rules': typeof AppPolicyRulesRoute
  '/relays/embedded': typeof AppRelaysEmbeddedRoute
  '/relays/latency': typeof AppRelaysLatencyRoute
  '/relays/map': typeof AppRelaysMapRoute
  '/relays/own': typeof AppRelaysOwnRoute
  '/relays/sources': typeof AppRelaysSourcesRoute
  '/services/$label': typeof AppServicesLabelRoute
  '/settings/server': typeof AppSettingsServerRoute
  '/settings/tailnet': typeof AppSettingsTailnetRoute
  '/dns/': typeof AppDnsIndexRoute
  '/integrations/': typeof AppIntegrationsIndexRoute
  '/keys/': typeof AppKeysIndexRoute
  '/machines/': typeof AppMachinesIndexRoute
  '/policy/': typeof AppPolicyIndexRoute
  '/relays/': typeof AppRelaysIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/machines/$nodeId/ssh': typeof AppMachinesNodeIdSshRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/apps': typeof AppAppsRoute
  '/audit': typeof AppAuditRoute
  '/networks': typeof AppNetworksRoute
  '/routes': typeof AppRoutesRoute
  '/sessions': typeof AppSessionsRoute
  '/sign-ins': typeof AppSignInsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/dns/nameservers': typeof AppDnsNameserversRoute
  '/dns/records': typeof AppDnsRecordsRoute
  '/dns/split': typeof AppDnsSplitRoute
  '/integrations/log-streams': typeof AppIntegrationsLogStreamsRoute
  '/integrations/posture': typeof AppIntegrationsPostureRoute
  '/integrations/webhooks': typeof AppIntegrationsWebhooksRoute
  '/keys/api': typeof AppKeysApiRoute
  '/keys/oauth': typeof AppKeysOauthRoute
  '/keys/pre-auth': typeof AppKeysPreAuthRoute
  '/machines/$nodeId': typeof AppMachinesNodeIdRoute
  '/policy/file': typeof AppPolicyFileRoute
  '/policy/graph': typeof AppPolicyGraphRoute
  '/policy/groups': typeof AppPolicyGroupsRoute
  '/policy/postures': typeof AppPolicyPosturesRoute
  '/policy/requests': typeof AppPolicyRequestsRoute
  '/policy/rules': typeof AppPolicyRulesRoute
  '/relays/embedded': typeof AppRelaysEmbeddedRoute
  '/relays/latency': typeof AppRelaysLatencyRoute
  '/relays/map': typeof AppRelaysMapRoute
  '/relays/own': typeof AppRelaysOwnRoute
  '/relays/sources': typeof AppRelaysSourcesRoute
  '/services/$label': typeof AppServicesLabelRoute
  '/settings/server': typeof AppSettingsServerRoute
  '/settings/tailnet': typeof AppSettingsTailnetRoute
  '/dns': typeof AppDnsIndexRoute
  '/integrations': typeof AppIntegrationsIndexRoute
  '/keys': typeof AppKeysIndexRoute
  '/machines': typeof AppMachinesIndexRoute
  '/policy': typeof AppPolicyIndexRoute
  '/relays': typeof AppRelaysIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/machines/$nodeId/ssh': typeof AppMachinesNodeIdSshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/apps': typeof AppAppsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/networks': typeof AppNetworksRoute
  '/_app/routes': typeof AppRoutesRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/sign-ins': typeof AppSignInsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/dns/nameservers': typeof AppDnsNameserversRoute
  '/_app/dns/records': typeof AppDnsRecordsRoute
  '/_app/dns/split': typeof AppDnsSplitRoute
  '/_app/integrations/log-streams': typeof AppIntegrationsLogStreamsRoute
  '/_app/integrations/posture': typeof AppIntegrationsPostureRoute
  '/_app/integrations/webhooks': typeof AppIntegrationsWebhooksRoute
  '/_app/keys/api': typeof AppKeysApiRoute
  '/_app/keys/oauth': typeof AppKeysOauthRoute
  '/_app/keys/pre-auth': typeof AppKeysPreAuthRoute
  '/_app/machines/$nodeId': typeof AppMachinesNodeIdRoute
  '/_app/policy/file': typeof AppPolicyFileRoute
  '/_app/policy/graph': typeof AppPolicyGraphRoute
  '/_app/policy/groups': typeof AppPolicyGroupsRoute
  '/_app/policy/postures': typeof AppPolicyPosturesRoute
  '/_app/policy/requests': typeof AppPolicyRequestsRoute
  '/_app/policy/rules': typeof AppPolicyRulesRoute
  '/_app/relays/embedded': typeof AppRelaysEmbeddedRoute
  '/_app/relays/latency': typeof AppRelaysLatencyRoute
  '/_app/relays/map': typeof AppRelaysMapRoute
  '/_app/relays/own': typeof AppRelaysOwnRoute
  '/_app/relays/sources': typeof AppRelaysSourcesRoute
  '/_app/services/$label': typeof AppServicesLabelRoute
  '/_app/settings/server': typeof AppSettingsServerRoute
  '/_app/settings/tailnet': typeof AppSettingsTailnetRoute
  '/_app/dns/': typeof AppDnsIndexRoute
  '/_app/integrations/': typeof AppIntegrationsIndexRoute
  '/_app/keys/': typeof AppKeysIndexRoute
  '/_app/machines/': typeof AppMachinesIndexRoute
  '/_app/policy/': typeof AppPolicyIndexRoute
  '/_app/relays/': typeof AppRelaysIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/machines/$nodeId_/ssh': typeof AppMachinesNodeIdSshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/access'
    | '/apps'
    | '/audit'
    | '/networks'
    | '/routes'
    | '/sessions'
    | '/sign-ins'
    | '/users'
    | '/dns/nameservers'
    | '/dns/records'
    | '/dns/split'
    | '/integrations/log-streams'
    | '/integrations/posture'
    | '/integrations/webhooks'
    | '/keys/api'
    | '/keys/oauth'
    | '/keys/pre-auth'
    | '/machines/$nodeId'
    | '/policy/file'
    | '/policy/graph'
    | '/policy/groups'
    | '/policy/postures'
    | '/policy/requests'
    | '/policy/rules'
    | '/relays/embedded'
    | '/relays/latency'
    | '/relays/map'
    | '/relays/own'
    | '/relays/sources'
    | '/services/$label'
    | '/settings/server'
    | '/settings/tailnet'
    | '/dns/'
    | '/integrations/'
    | '/keys/'
    | '/machines/'
    | '/policy/'
    | '/relays/'
    | '/services/'
    | '/settings/'
    | '/machines/$nodeId/ssh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/access'
    | '/apps'
    | '/audit'
    | '/networks'
    | '/routes'
    | '/sessions'
    | '/sign-ins'
    | '/users'
    | '/'
    | '/dns/nameservers'
    | '/dns/records'
    | '/dns/split'
    | '/integrations/log-streams'
    | '/integrations/posture'
    | '/integrations/webhooks'
    | '/keys/api'
    | '/keys/oauth'
    | '/keys/pre-auth'
    | '/machines/$nodeId'
    | '/policy/file'
    | '/policy/graph'
    | '/policy/groups'
    | '/policy/postures'
    | '/policy/requests'
    | '/policy/rules'
    | '/relays/embedded'
    | '/relays/latency'
    | '/relays/map'
    | '/relays/own'
    | '/relays/sources'
    | '/services/$label'
    | '/settings/server'
    | '/settings/tailnet'
    | '/dns'
    | '/integrations'
    | '/keys'
    | '/machines'
    | '/policy'
    | '/relays'
    | '/services'
    | '/settings'
    | '/machines/$nodeId/ssh'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$'
    | '/_app/access'
    | '/_app/apps'
    | '/_app/audit'
    | '/_app/networks'
    | '/_app/routes'
    | '/_app/sessions'
    | '/_app/sign-ins'
    | '/_app/users'
    | '/_app/'
    | '/_app/dns/nameservers'
    | '/_app/dns/records'
    | '/_app/dns/split'
    | '/_app/integrations/log-streams'
    | '/_app/integrations/posture'
    | '/_app/integrations/webhooks'
    | '/_app/keys/api'
    | '/_app/keys/oauth'
    | '/_app/keys/pre-auth'
    | '/_app/machines/$nodeId'
    | '/_app/policy/file'
    | '/_app/policy/graph'
    | '/_app/policy/groups'
    | '/_app/policy/postures'
    | '/_app/policy/requests'
    | '/_app/policy/rules'
    | '/_app/relays/embedded'
    | '/_app/relays/latency'
    | '/_app/relays/map'
    | '/_app/relays/own'
    | '/_app/relays/sources'
    | '/_app/services/$label'
    | '/_app/settings/server'
    | '/_app/settings/tailnet'
    | '/_app/dns/'
    | '/_app/integrations/'
    | '/_app/keys/'
    | '/_app/machines/'
    | '/_app/policy/'
    | '/_app/relays/'
    | '/_app/services/'
    | '/_app/settings/'
    | '/_app/machines/$nodeId_/ssh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps': {
      id: '/_app/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networks': {
      id: '/_app/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof AppNetworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes': {
      id: '/_app/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-ins': {
      id: '/_app/sign-ins'
      path: '/sign-ins'
      fullPath: '/sign-ins'
      preLoaderRoute: typeof AppSignInsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dns/': {
      id: '/_app/dns/'
      path: '/dns'
      fullPath: '/dns/'
      preLoaderRoute: typeof AppDnsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dns/nameservers': {
      id: '/_app/dns/nameservers'
      path: '/dns/nameservers'
      fullPath: '/dns/nameservers'
      preLoaderRoute: typeof AppDnsNameserversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dns/records': {
      id: '/_app/dns/records'
      path: '/dns/records'
      fullPath: '/dns/records'
      preLoaderRoute: typeof AppDnsRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dns/split': {
      id: '/_app/dns/split'
      path: '/dns/split'
      fullPath: '/dns/split'
      preLoaderRoute: typeof AppDnsSplitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/': {
      id: '/_app/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/log-streams': {
      id: '/_app/integrations/log-streams'
      path: '/integrations/log-streams'
      fullPath: '/integrations/log-streams'
      preLoaderRoute: typeof AppIntegrationsLogStreamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/posture': {
      id: '/_app/integrations/posture'
      path: '/integrations/posture'
      fullPath: '/integrations/posture'
      preLoaderRoute: typeof AppIntegrationsPostureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/webhooks': {
      id: '/_app/integrations/webhooks'
      path: '/integrations/webhooks'
      fullPath: '/integrations/webhooks'
      preLoaderRoute: typeof AppIntegrationsWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys/': {
      id: '/_app/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof AppKeysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys/api': {
      id: '/_app/keys/api'
      path: '/keys/api'
      fullPath: '/keys/api'
      preLoaderRoute: typeof AppKeysApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys/oauth': {
      id: '/_app/keys/oauth'
      path: '/keys/oauth'
      fullPath: '/keys/oauth'
      preLoaderRoute: typeof AppKeysOauthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys/pre-auth': {
      id: '/_app/keys/pre-auth'
      path: '/keys/pre-auth'
      fullPath: '/keys/pre-auth'
      preLoaderRoute: typeof AppKeysPreAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines/': {
      id: '/_app/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof AppMachinesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines/$nodeId': {
      id: '/_app/machines/$nodeId'
      path: '/machines/$nodeId'
      fullPath: '/machines/$nodeId'
      preLoaderRoute: typeof AppMachinesNodeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/': {
      id: '/_app/policy/'
      path: '/policy'
      fullPath: '/policy/'
      preLoaderRoute: typeof AppPolicyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/file': {
      id: '/_app/policy/file'
      path: '/policy/file'
      fullPath: '/policy/file'
      preLoaderRoute: typeof AppPolicyFileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/graph': {
      id: '/_app/policy/graph'
      path: '/policy/graph'
      fullPath: '/policy/graph'
      preLoaderRoute: typeof AppPolicyGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/groups': {
      id: '/_app/policy/groups'
      path: '/policy/groups'
      fullPath: '/policy/groups'
      preLoaderRoute: typeof AppPolicyGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/postures': {
      id: '/_app/policy/postures'
      path: '/policy/postures'
      fullPath: '/policy/postures'
      preLoaderRoute: typeof AppPolicyPosturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/requests': {
      id: '/_app/policy/requests'
      path: '/policy/requests'
      fullPath: '/policy/requests'
      preLoaderRoute: typeof AppPolicyRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/rules': {
      id: '/_app/policy/rules'
      path: '/policy/rules'
      fullPath: '/policy/rules'
      preLoaderRoute: typeof AppPolicyRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relays/': {
      id: '/_app/relays/'
      path: '/relays'
      fullPath: '/relays/'
      preLoaderRoute: typeof AppRelaysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relays/embedded': {
      id: '/_app/relays/embedded'
      path: '/relays/embedded'
      fullPath: '/relays/embedded'
      preLoaderRoute: typeof AppRelaysEmbeddedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relays/latency': {
      id: '/_app/relays/latency'
      path: '/relays/latency'
      fullPath: '/relays/latency'
      preLoaderRoute: typeof AppRelaysLatencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relays/map': {
      id: '/_app/relays/map'
      path: '/relays/map'
      fullPath: '/relays/map'
      preLoaderRoute: typeof AppRelaysMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relays/own': {
      id: '/_app/relays/own'
      path: '/relays/own'
      fullPath: '/relays/own'
      preLoaderRoute: typeof AppRelaysOwnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relays/sources': {
      id: '/_app/relays/sources'
      path: '/relays/sources'
      fullPath: '/relays/sources'
      preLoaderRoute: typeof AppRelaysSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$label': {
      id: '/_app/services/$label'
      path: '/services/$label'
      fullPath: '/services/$label'
      preLoaderRoute: typeof AppServicesLabelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/server': {
      id: '/_app/settings/server'
      path: '/settings/server'
      fullPath: '/settings/server'
      preLoaderRoute: typeof AppSettingsServerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/tailnet': {
      id: '/_app/settings/tailnet'
      path: '/settings/tailnet'
      fullPath: '/settings/tailnet'
      preLoaderRoute: typeof AppSettingsTailnetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines/$nodeId_/ssh': {
      id: '/_app/machines/$nodeId_/ssh'
      path: '/machines/$nodeId/ssh'
      fullPath: '/machines/$nodeId/ssh'
      preLoaderRoute: typeof AppMachinesNodeIdSshRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAccessRoute: typeof AppAccessRoute
  AppAppsRoute: typeof AppAppsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppNetworksRoute: typeof AppNetworksRoute
  AppRoutesRoute: typeof AppRoutesRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSignInsRoute: typeof AppSignInsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDnsNameserversRoute: typeof AppDnsNameserversRoute
  AppDnsRecordsRoute: typeof AppDnsRecordsRoute
  AppDnsSplitRoute: typeof AppDnsSplitRoute
  AppIntegrationsLogStreamsRoute: typeof AppIntegrationsLogStreamsRoute
  AppIntegrationsPostureRoute: typeof AppIntegrationsPostureRoute
  AppIntegrationsWebhooksRoute: typeof AppIntegrationsWebhooksRoute
  AppKeysApiRoute: typeof AppKeysApiRoute
  AppKeysOauthRoute: typeof AppKeysOauthRoute
  AppKeysPreAuthRoute: typeof AppKeysPreAuthRoute
  AppMachinesNodeIdRoute: typeof AppMachinesNodeIdRoute
  AppPolicyFileRoute: typeof AppPolicyFileRoute
  AppPolicyGraphRoute: typeof AppPolicyGraphRoute
  AppPolicyGroupsRoute: typeof AppPolicyGroupsRoute
  AppPolicyPosturesRoute: typeof AppPolicyPosturesRoute
  AppPolicyRequestsRoute: typeof AppPolicyRequestsRoute
  AppPolicyRulesRoute: typeof AppPolicyRulesRoute
  AppRelaysEmbeddedRoute: typeof AppRelaysEmbeddedRoute
  AppRelaysLatencyRoute: typeof AppRelaysLatencyRoute
  AppRelaysMapRoute: typeof AppRelaysMapRoute
  AppRelaysOwnRoute: typeof AppRelaysOwnRoute
  AppRelaysSourcesRoute: typeof AppRelaysSourcesRoute
  AppServicesLabelRoute: typeof AppServicesLabelRoute
  AppSettingsServerRoute: typeof AppSettingsServerRoute
  AppSettingsTailnetRoute: typeof AppSettingsTailnetRoute
  AppDnsIndexRoute: typeof AppDnsIndexRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppKeysIndexRoute: typeof AppKeysIndexRoute
  AppMachinesIndexRoute: typeof AppMachinesIndexRoute
  AppPolicyIndexRoute: typeof AppPolicyIndexRoute
  AppRelaysIndexRoute: typeof AppRelaysIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppMachinesNodeIdSshRoute: typeof AppMachinesNodeIdSshRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAccessRoute: AppAccessRoute,
  AppAppsRoute: AppAppsRoute,
  AppAuditRoute: AppAuditRoute,
  AppNetworksRoute: AppNetworksRoute,
  AppRoutesRoute: AppRoutesRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSignInsRoute: AppSignInsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppDnsNameserversRoute: AppDnsNameserversRoute,
  AppDnsRecordsRoute: AppDnsRecordsRoute,
  AppDnsSplitRoute: AppDnsSplitRoute,
  AppIntegrationsLogStreamsRoute: AppIntegrationsLogStreamsRoute,
  AppIntegrationsPostureRoute: AppIntegrationsPostureRoute,
  AppIntegrationsWebhooksRoute: AppIntegrationsWebhooksRoute,
  AppKeysApiRoute: AppKeysApiRoute,
  AppKeysOauthRoute: AppKeysOauthRoute,
  AppKeysPreAuthRoute: AppKeysPreAuthRoute,
  AppMachinesNodeIdRoute: AppMachinesNodeIdRoute,
  AppPolicyFileRoute: AppPolicyFileRoute,
  AppPolicyGraphRoute: AppPolicyGraphRoute,
  AppPolicyGroupsRoute: AppPolicyGroupsRoute,
  AppPolicyPosturesRoute: AppPolicyPosturesRoute,
  AppPolicyRequestsRoute: AppPolicyRequestsRoute,
  AppPolicyRulesRoute: AppPolicyRulesRoute,
  AppRelaysEmbeddedRoute: AppRelaysEmbeddedRoute,
  AppRelaysLatencyRoute: AppRelaysLatencyRoute,
  AppRelaysMapRoute: AppRelaysMapRoute,
  AppRelaysOwnRoute: AppRelaysOwnRoute,
  AppRelaysSourcesRoute: AppRelaysSourcesRoute,
  AppServicesLabelRoute: AppServicesLabelRoute,
  AppSettingsServerRoute: AppSettingsServerRoute,
  AppSettingsTailnetRoute: AppSettingsTailnetRoute,
  AppDnsIndexRoute: AppDnsIndexRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppKeysIndexRoute: AppKeysIndexRoute,
  AppMachinesIndexRoute: AppMachinesIndexRoute,
  AppPolicyIndexRoute: AppPolicyIndexRoute,
  AppRelaysIndexRoute: AppRelaysIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppMachinesNodeIdSshRoute: AppMachinesNodeIdSshRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
