/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppDnsRouteImport } from './routes/_app/dns'
import { Route as AppNetworksRouteImport } from './routes/_app/networks'
import { Route as AppRelaysRouteImport } from './routes/_app/relays'
import { Route as AppRoutesRouteImport } from './routes/_app/routes'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppIntegrationsIndexRouteImport } from './routes/_app/integrations/index'
import { Route as AppIntegrationsLogStreamsRouteImport } from './routes/_app/integrations/log-streams'
import { Route as AppIntegrationsWebhooksRouteImport } from './routes/_app/integrations/webhooks'
import { Route as AppKeysIndexRouteImport } from './routes/_app/keys/index'
import { Route as AppKeysApiRouteImport } from './routes/_app/keys/api'
import { Route as AppKeysOauthRouteImport } from './routes/_app/keys/oauth'
import { Route as AppKeysPreAuthRouteImport } from './routes/_app/keys/pre-auth'
import { Route as AppMachinesIndexRouteImport } from './routes/_app/machines/index'
import { Route as AppMachinesNodeIdRouteImport } from './routes/_app/machines/$nodeId'
import { Route as AppPolicyIndexRouteImport } from './routes/_app/policy/index'
import { Route as AppPolicyFileRouteImport } from './routes/_app/policy/file'
import { Route as AppPolicyGroupsRouteImport } from './routes/_app/policy/groups'
import { Route as AppPolicyPosturesRouteImport } from './routes/_app/policy/postures'
import { Route as AppPolicyRequestsRouteImport } from './routes/_app/policy/requests'
import { Route as AppPolicyRulesRouteImport } from './routes/_app/policy/rules'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDnsRoute = AppDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksRoute = AppNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => AppRoute,
} as any)
const AppRelaysRoute = AppRelaysRouteImport.update({
  id: '/relays',
  path: '/relays',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRoute = AppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsLogStreamsRoute =
  AppIntegrationsLogStreamsRouteImport.update({
    id: '/integrations/log-streams',
    path: '/integrations/log-streams',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntegrationsWebhooksRoute = AppIntegrationsWebhooksRouteImport.update({
  id: '/integrations/webhooks',
  path: '/integrations/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysIndexRoute = AppKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysApiRoute = AppKeysApiRouteImport.update({
  id: '/keys/api',
  path: '/keys/api',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysOauthRoute = AppKeysOauthRouteImport.update({
  id: '/keys/oauth',
  path: '/keys/oauth',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysPreAuthRoute = AppKeysPreAuthRouteImport.update({
  id: '/keys/pre-auth',
  path: '/keys/pre-auth',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesIndexRoute = AppMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesNodeIdRoute = AppMachinesNodeIdRouteImport.update({
  id: '/machines/$nodeId',
  path: '/machines/$nodeId',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyIndexRoute = AppPolicyIndexRouteImport.update({
  id: '/policy/',
  path: '/policy/',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyFileRoute = AppPolicyFileRouteImport.update({
  id: '/policy/file',
  path: '/policy/file',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyGroupsRoute = AppPolicyGroupsRouteImport.update({
  id: '/policy/groups',
  path: '/policy/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyPosturesRoute = AppPolicyPosturesRouteImport.update({
  id: '/policy/postures',
  path: '/policy/postures',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyRequestsRoute = AppPolicyRequestsRouteImport.update({
  id: '/policy/requests',
  path: '/policy/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyRulesRoute = AppPolicyRulesRouteImport.update({
  id: '/policy/rules',
  path: '/policy/rules',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/audit': typeof AppAuditRoute
  '/dns': typeof AppDnsRoute
  '/networks': typeof AppNetworksRoute
  '/relays': typeof AppRelaysRoute
  '/routes': typeof AppRoutesRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/integrations/log-streams': typeof AppIntegrationsLogStreamsRoute
  '/integrations/webhooks': typeof AppIntegrationsWebhooksRoute
  '/keys/api': typeof AppKeysApiRoute
  '/keys/oauth': typeof AppKeysOauthRoute
  '/keys/pre-auth': typeof AppKeysPreAuthRoute
  '/machines/$nodeId': typeof AppMachinesNodeIdRoute
  '/policy/file': typeof AppPolicyFileRoute
  '/policy/groups': typeof AppPolicyGroupsRoute
  '/policy/postures': typeof AppPolicyPosturesRoute
  '/policy/requests': typeof AppPolicyRequestsRoute
  '/policy/rules': typeof AppPolicyRulesRoute
  '/integrations/': typeof AppIntegrationsIndexRoute
  '/keys/': typeof AppKeysIndexRoute
  '/machines/': typeof AppMachinesIndexRoute
  '/policy/': typeof AppPolicyIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/access': typeof AppAccessRoute
  '/audit': typeof AppAuditRoute
  '/dns': typeof AppDnsRoute
  '/networks': typeof AppNetworksRoute
  '/relays': typeof AppRelaysRoute
  '/routes': typeof AppRoutesRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/integrations/log-streams': typeof AppIntegrationsLogStreamsRoute
  '/integrations/webhooks': typeof AppIntegrationsWebhooksRoute
  '/keys/api': typeof AppKeysApiRoute
  '/keys/oauth': typeof AppKeysOauthRoute
  '/keys/pre-auth': typeof AppKeysPreAuthRoute
  '/machines/$nodeId': typeof AppMachinesNodeIdRoute
  '/policy/file': typeof AppPolicyFileRoute
  '/policy/groups': typeof AppPolicyGroupsRoute
  '/policy/postures': typeof AppPolicyPosturesRoute
  '/policy/requests': typeof AppPolicyRequestsRoute
  '/policy/rules': typeof AppPolicyRulesRoute
  '/integrations': typeof AppIntegrationsIndexRoute
  '/keys': typeof AppKeysIndexRoute
  '/machines': typeof AppMachinesIndexRoute
  '/policy': typeof AppPolicyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dns': typeof AppDnsRoute
  '/_app/networks': typeof AppNetworksRoute
  '/_app/relays': typeof AppRelaysRoute
  '/_app/routes': typeof AppRoutesRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/integrations/log-streams': typeof AppIntegrationsLogStreamsRoute
  '/_app/integrations/webhooks': typeof AppIntegrationsWebhooksRoute
  '/_app/keys/api': typeof AppKeysApiRoute
  '/_app/keys/oauth': typeof AppKeysOauthRoute
  '/_app/keys/pre-auth': typeof AppKeysPreAuthRoute
  '/_app/machines/$nodeId': typeof AppMachinesNodeIdRoute
  '/_app/policy/file': typeof AppPolicyFileRoute
  '/_app/policy/groups': typeof AppPolicyGroupsRoute
  '/_app/policy/postures': typeof AppPolicyPosturesRoute
  '/_app/policy/requests': typeof AppPolicyRequestsRoute
  '/_app/policy/rules': typeof AppPolicyRulesRoute
  '/_app/integrations/': typeof AppIntegrationsIndexRoute
  '/_app/keys/': typeof AppKeysIndexRoute
  '/_app/machines/': typeof AppMachinesIndexRoute
  '/_app/policy/': typeof AppPolicyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/access'
    | '/audit'
    | '/dns'
    | '/networks'
    | '/relays'
    | '/routes'
    | '/sessions'
    | '/settings'
    | '/users'
    | '/integrations/log-streams'
    | '/integrations/webhooks'
    | '/keys/api'
    | '/keys/oauth'
    | '/keys/pre-auth'
    | '/machines/$nodeId'
    | '/policy/file'
    | '/policy/groups'
    | '/policy/postures'
    | '/policy/requests'
    | '/policy/rules'
    | '/integrations/'
    | '/keys/'
    | '/machines/'
    | '/policy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/access'
    | '/audit'
    | '/dns'
    | '/networks'
    | '/relays'
    | '/routes'
    | '/sessions'
    | '/settings'
    | '/users'
    | '/'
    | '/integrations/log-streams'
    | '/integrations/webhooks'
    | '/keys/api'
    | '/keys/oauth'
    | '/keys/pre-auth'
    | '/machines/$nodeId'
    | '/policy/file'
    | '/policy/groups'
    | '/policy/postures'
    | '/policy/requests'
    | '/policy/rules'
    | '/integrations'
    | '/keys'
    | '/machines'
    | '/policy'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$'
    | '/_app/access'
    | '/_app/audit'
    | '/_app/dns'
    | '/_app/networks'
    | '/_app/relays'
    | '/_app/routes'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/'
    | '/_app/integrations/log-streams'
    | '/_app/integrations/webhooks'
    | '/_app/keys/api'
    | '/_app/keys/oauth'
    | '/_app/keys/pre-auth'
    | '/_app/machines/$nodeId'
    | '/_app/policy/file'
    | '/_app/policy/groups'
    | '/_app/policy/postures'
    | '/_app/policy/requests'
    | '/_app/policy/rules'
    | '/_app/integrations/'
    | '/_app/keys/'
    | '/_app/machines/'
    | '/_app/policy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dns': {
      id: '/_app/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof AppDnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networks': {
      id: '/_app/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof AppNetworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relays': {
      id: '/_app/relays'
      path: '/relays'
      fullPath: '/relays'
      preLoaderRoute: typeof AppRelaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes': {
      id: '/_app/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AppRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/': {
      id: '/_app/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/log-streams': {
      id: '/_app/integrations/log-streams'
      path: '/integrations/log-streams'
      fullPath: '/integrations/log-streams'
      preLoaderRoute: typeof AppIntegrationsLogStreamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/webhooks': {
      id: '/_app/integrations/webhooks'
      path: '/integrations/webhooks'
      fullPath: '/integrations/webhooks'
      preLoaderRoute: typeof AppIntegrationsWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys/': {
      id: '/_app/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof AppKeysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys/api': {
      id: '/_app/keys/api'
      path: '/keys/api'
      fullPath: '/keys/api'
      preLoaderRoute: typeof AppKeysApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys/oauth': {
      id: '/_app/keys/oauth'
      path: '/keys/oauth'
      fullPath: '/keys/oauth'
      preLoaderRoute: typeof AppKeysOauthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys/pre-auth': {
      id: '/_app/keys/pre-auth'
      path: '/keys/pre-auth'
      fullPath: '/keys/pre-auth'
      preLoaderRoute: typeof AppKeysPreAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines/': {
      id: '/_app/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof AppMachinesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines/$nodeId': {
      id: '/_app/machines/$nodeId'
      path: '/machines/$nodeId'
      fullPath: '/machines/$nodeId'
      preLoaderRoute: typeof AppMachinesNodeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/': {
      id: '/_app/policy/'
      path: '/policy'
      fullPath: '/policy/'
      preLoaderRoute: typeof AppPolicyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/file': {
      id: '/_app/policy/file'
      path: '/policy/file'
      fullPath: '/policy/file'
      preLoaderRoute: typeof AppPolicyFileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/groups': {
      id: '/_app/policy/groups'
      path: '/policy/groups'
      fullPath: '/policy/groups'
      preLoaderRoute: typeof AppPolicyGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/postures': {
      id: '/_app/policy/postures'
      path: '/policy/postures'
      fullPath: '/policy/postures'
      preLoaderRoute: typeof AppPolicyPosturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/requests': {
      id: '/_app/policy/requests'
      path: '/policy/requests'
      fullPath: '/policy/requests'
      preLoaderRoute: typeof AppPolicyRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy/rules': {
      id: '/_app/policy/rules'
      path: '/policy/rules'
      fullPath: '/policy/rules'
      preLoaderRoute: typeof AppPolicyRulesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAccessRoute: typeof AppAccessRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDnsRoute: typeof AppDnsRoute
  AppNetworksRoute: typeof AppNetworksRoute
  AppRelaysRoute: typeof AppRelaysRoute
  AppRoutesRoute: typeof AppRoutesRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIntegrationsLogStreamsRoute: typeof AppIntegrationsLogStreamsRoute
  AppIntegrationsWebhooksRoute: typeof AppIntegrationsWebhooksRoute
  AppKeysApiRoute: typeof AppKeysApiRoute
  AppKeysOauthRoute: typeof AppKeysOauthRoute
  AppKeysPreAuthRoute: typeof AppKeysPreAuthRoute
  AppMachinesNodeIdRoute: typeof AppMachinesNodeIdRoute
  AppPolicyFileRoute: typeof AppPolicyFileRoute
  AppPolicyGroupsRoute: typeof AppPolicyGroupsRoute
  AppPolicyPosturesRoute: typeof AppPolicyPosturesRoute
  AppPolicyRequestsRoute: typeof AppPolicyRequestsRoute
  AppPolicyRulesRoute: typeof AppPolicyRulesRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppKeysIndexRoute: typeof AppKeysIndexRoute
  AppMachinesIndexRoute: typeof AppMachinesIndexRoute
  AppPolicyIndexRoute: typeof AppPolicyIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAccessRoute: AppAccessRoute,
  AppAuditRoute: AppAuditRoute,
  AppDnsRoute: AppDnsRoute,
  AppNetworksRoute: AppNetworksRoute,
  AppRelaysRoute: AppRelaysRoute,
  AppRoutesRoute: AppRoutesRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppIntegrationsLogStreamsRoute: AppIntegrationsLogStreamsRoute,
  AppIntegrationsWebhooksRoute: AppIntegrationsWebhooksRoute,
  AppKeysApiRoute: AppKeysApiRoute,
  AppKeysOauthRoute: AppKeysOauthRoute,
  AppKeysPreAuthRoute: AppKeysPreAuthRoute,
  AppMachinesNodeIdRoute: AppMachinesNodeIdRoute,
  AppPolicyFileRoute: AppPolicyFileRoute,
  AppPolicyGroupsRoute: AppPolicyGroupsRoute,
  AppPolicyPosturesRoute: AppPolicyPosturesRoute,
  AppPolicyRequestsRoute: AppPolicyRequestsRoute,
  AppPolicyRulesRoute: AppPolicyRulesRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppKeysIndexRoute: AppKeysIndexRoute,
  AppMachinesIndexRoute: AppMachinesIndexRoute,
  AppPolicyIndexRoute: AppPolicyIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
