/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppDnsRouteImport } from './routes/_app/dns'
import { Route as AppKeysRouteImport } from './routes/_app/keys'
import { Route as AppNetworksRouteImport } from './routes/_app/networks'
import { Route as AppPolicyRouteImport } from './routes/_app/policy'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppWebhooksRouteImport } from './routes/_app/webhooks'
import { Route as AppMachinesIndexRouteImport } from './routes/_app/machines/index'
import { Route as AppMachinesNodeIdRouteImport } from './routes/_app/machines/$nodeId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDnsRoute = AppDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksRoute = AppNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => AppRoute,
} as any)
const AppPolicyRoute = AppPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesIndexRoute = AppMachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => AppRoute,
} as any)
const AppMachinesNodeIdRoute = AppMachinesNodeIdRouteImport.update({
  id: '/machines/$nodeId',
  path: '/machines/$nodeId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/audit': typeof AppAuditRoute
  '/dns': typeof AppDnsRoute
  '/keys': typeof AppKeysRoute
  '/networks': typeof AppNetworksRoute
  '/policy': typeof AppPolicyRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/webhooks': typeof AppWebhooksRoute
  '/machines/$nodeId': typeof AppMachinesNodeIdRoute
  '/machines/': typeof AppMachinesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/audit': typeof AppAuditRoute
  '/dns': typeof AppDnsRoute
  '/keys': typeof AppKeysRoute
  '/networks': typeof AppNetworksRoute
  '/policy': typeof AppPolicyRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/webhooks': typeof AppWebhooksRoute
  '/': typeof AppIndexRoute
  '/machines/$nodeId': typeof AppMachinesNodeIdRoute
  '/machines': typeof AppMachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dns': typeof AppDnsRoute
  '/_app/keys': typeof AppKeysRoute
  '/_app/networks': typeof AppNetworksRoute
  '/_app/policy': typeof AppPolicyRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/machines/$nodeId': typeof AppMachinesNodeIdRoute
  '/_app/machines/': typeof AppMachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/audit'
    | '/dns'
    | '/keys'
    | '/networks'
    | '/policy'
    | '/settings'
    | '/users'
    | '/webhooks'
    | '/machines/$nodeId'
    | '/machines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/access'
    | '/audit'
    | '/dns'
    | '/keys'
    | '/networks'
    | '/policy'
    | '/settings'
    | '/users'
    | '/webhooks'
    | '/'
    | '/machines/$nodeId'
    | '/machines'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/access'
    | '/_app/audit'
    | '/_app/dns'
    | '/_app/keys'
    | '/_app/networks'
    | '/_app/policy'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/webhooks'
    | '/_app/'
    | '/_app/machines/$nodeId'
    | '/_app/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dns': {
      id: '/_app/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof AppDnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networks': {
      id: '/_app/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof AppNetworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policy': {
      id: '/_app/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof AppPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines/': {
      id: '/_app/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof AppMachinesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/machines/$nodeId': {
      id: '/_app/machines/$nodeId'
      path: '/machines/$nodeId'
      fullPath: '/machines/$nodeId'
      preLoaderRoute: typeof AppMachinesNodeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDnsRoute: typeof AppDnsRoute
  AppKeysRoute: typeof AppKeysRoute
  AppNetworksRoute: typeof AppNetworksRoute
  AppPolicyRoute: typeof AppPolicyRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMachinesNodeIdRoute: typeof AppMachinesNodeIdRoute
  AppMachinesIndexRoute: typeof AppMachinesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppAuditRoute: AppAuditRoute,
  AppDnsRoute: AppDnsRoute,
  AppKeysRoute: AppKeysRoute,
  AppNetworksRoute: AppNetworksRoute,
  AppPolicyRoute: AppPolicyRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
  AppMachinesNodeIdRoute: AppMachinesNodeIdRoute,
  AppMachinesIndexRoute: AppMachinesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
