// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$zO]QPOOOOQO'#Cd'#CdOtQPO'#CgO|QPO'#CnOOQO'#Ct'#CtQOQPOOOOQO'#Ci'#CiO!TQPO'#ChO!YQPO'#CvOOQO,59R,59RO!bQPO,59RO!gQPO'#CwOOQO,59Y,59YO!oQPO,59YO]QPO,59SO!tQPO,59bO!|QPO,59bOOQO1G.m1G.mO#UQPO,59cO#]QPO,59cOOQO1G.t1G.tOOQO1G.n1G.nOOQO,59Z,59ZO#eQPO1G.|OOQO-E6m-E6mOOQO,59[,59[O#mQPO1G.}OOQO-E6n-E6nPwQPO'#CoP]QPO'#Cp",
  stateData: "#t~OgOSPOSQOS~OSSOTSOUSOVSOYQOaROiPO~OXXOiUO~O`[O~P]O^^O~O__OXjX~OXaO~O_bO`kX~O`dO~OiUOXja~O_gOXja~O`ka~P]O_jO`ka~OiUOXji~O`ki~P]O",
  goto: "!ulPPPPPPPPmPPmu}PPPPm!T!ZPPP!aP!o!r]SOR^bjmQWQVf_glXVQ_glQ`WRh`QcZRkcQTOQZRQe^VibjmRYQR]R",
  nodeNames: "⚠ LineComment BlockComment HuJSON True False Null Number String } { Object Property PropertyName : , ] [ Array",
  maxTerm: 27,
  nodeProps: [
    ["isolate", -2,8,13,""],
    ["openedBy", 9,"{",16,"["],
    ["closedBy", 10,"}",17,"]"]
  ],
  skippedNodes: [0,1,2],
  repeatNodeCount: 2,
  tokenData: "*x~RbXY!ZYZ!Z]^!Zpq!Zrs!`|}$x}!O$}!P!Q&w!Q!R%W!R![&f![!](p!}#O(u#P#Q(z#Y#Z)P#b#c)n#h#i*V#o#p*n#q#r*s~!`Og~~!cWpq!`qr!`rs!{s#O!`#O#P#Q#P;'S!`;'S;=`$r<%lO!`~#QOi~~#TXrs!`!P!Q!`#O#P!`#U#V!`#Y#Z!`#b#c!`#f#g!`#h#i!`#i#j#p~#sR!Q![#|!c!i#|#T#Z#|~$PR!Q![$Y!c!i$Y#T#Z$Y~$]R!Q![$f!c!i$f#T#Z$f~$iR!Q![!`!c!i!`#T#Z!`~$uP;=`<%l!`~$}O_~~%QQ!Q!R%W!R![&f~%]RV~!O!P%f!g!h%z#X#Y%z~%iP!Q![%l~%qRV~!Q![%l!g!h%z#X#Y%z~%}R{|&W}!O&W!Q![&^~&ZP!Q![&^~&cPV~!Q![&^~&kSV~!O!P%f!Q![&f!g!h%z#X#Y%z~&zQz{'Q!P!Q(X~'TTOz'Qz{'d{;'S'Q;'S;=`(R<%lO'Q~'gVOz'Qz{'d{!P'Q!P!Q'|!Q;'S'Q;'S;=`(R<%lO'Q~(ROQ~~(UP;=`<%l'Q~(^SP~OY(XZ;'S(X;'S;=`(j<%lO(X~(mP;=`<%l(X~(uO^~~(zOa~~)PO`~~)SP#T#U)V~)YP#`#a)]~)`P#g#h)c~)fP#X#Y)i~)nOT~~)qP#i#j)t~)wP#`#a)z~)}P#`#a*Q~*VOU~~*YP#f#g*]~*`P#i#j*c~*fP#X#Y*i~*nOS~~*sOY~~*xOX~",
  tokenizers: [0],
  topRules: {"HuJSON":[0,3]},
  tokenPrec: 0
})
